package io.jenkins.plugins.jobconfigchain.safetynet;

import hudson.model.Result;
import io.jenkins.plugins.jobconfigchain.model.BaseConfigReference;
import io.jenkins.plugins.jobconfigchain.model.ConfigDeploymentBinding;
import io.jenkins.plugins.jobconfigchain.model.ConfigSet;
import io.jenkins.plugins.jobconfigchain.model.ResolvedBaseVersion;
import io.jenkins.plugins.jobconfigchain.persistence.ConfigDeploymentBindingRepository;
import io.jenkins.plugins.jobconfigchain.persistence.ConfigSetRepository;
import io.jenkins.plugins.jobconfigchain.ui.JobConfigTemplateProperty;
import org.jenkinsci.plugins.workflow.job.WorkflowJob;
import org.jenkinsci.plugins.workflow.job.WorkflowRun;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.jvnet.hudson.test.JenkinsRule;
import org.jvnet.hudson.test.junit.jupiter.WithJenkins;
import org.jvnet.hudson.test.junit.jupiter.WithLocalData;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

import static io.jenkins.plugins.jobconfigchain.safetynet.ChainTestKit.chainOf;
import static io.jenkins.plugins.jobconfigchain.safetynet.ChainTestKit.logBytes;
import static io.jenkins.plugins.jobconfigchain.safetynet.ChainTestKit.propertyOf;
import static io.jenkins.plugins.jobconfigchain.safetynet.ChainTestKit.runScript;
import static io.jenkins.plugins.jobconfigchain.safetynet.ChainTestKit.stepLogLines;
import static io.jenkins.plugins.jobconfigchain.safetynet.PinnedScenario.*;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Upgrade safety net: loads a Jenkins home that was PRODUCED BY THE PREVIOUS BUILD of the plugin (the
 * code before the review/security fixes, generated by {@link PinnedFixtureGeneratorTest}, not
 * hand-written — see {@code PROVENANCE.txt} in the fixture directory) with whatever code is in the
 * working tree now, and proves that nothing a user already has is lost or changed:
 * <ul>
 *   <li>the job's override property (config.xml), the plugin's storage directory (config sets,
 *       deployment bindings) and finished builds (build.xml with the stored setup action) load;</li>
 *   <li>new deploys on that home produce the SAME bytes and the SAME plugin console lines as the old
 *       code did (golden files recorded by the old code);</li>
 *   <li>redeploying an old build that was shipped by the old code replays exactly what it shipped;</li>
 *   <li>Pipeline builds that were suspended mid-run by the old code (program.dat + flow nodes written
 *       in the old format, setup state in build.xml) resume and finish with the golden output.</li>
 * </ul>
 *
 * <p>Characterization tests: green on the current code; they must stay green after every later phase.
 * Pipeline text uses the CURRENT step names; the scripts live in {@link PinnedScenario} (step names in
 * {@link ChainTestKit}), so a deliberate step rename is a one-line change there. Mixed-state tests with
 * the new names belong to the phase that introduces them.</p>
 */
@WithJenkins
public class UpgradeFromPinnedBuildTest {

    /** Simple name of the invisible Run action the setup step persists in build.xml. */
    static final String SETUP_ACTION_CLASS_SIMPLE_NAME = "ConfigTemplateSetupAction";

    private JenkinsRule j;

    @BeforeEach
    public void setUp(JenkinsRule rule) {
        j = rule;
    }

    private byte[] goldenBytes(String relativePath) throws IOException {
        return Files.readAllBytes(new File(j.jenkins.getRootDir(), relativePath).toPath());
    }

    private String goldenText(String relativePath) throws IOException {
        return new String(goldenBytes(relativePath), StandardCharsets.UTF_8);
    }

    private WorkflowJob job(String name) {
        WorkflowJob job = j.jenkins.getItemByFullName(name, WorkflowJob.class);
        assertNotNull(job, "job '" + name + "' from the pinned home must load");
        return job;
    }

    private void assertFinishedOldBuild(int number, String goldenKey) throws IOException {
        WorkflowRun run = job(JOB).getBuildByNumber(number);
        assertNotNull(run, "old build #" + number + " must load");
        assertEquals(Result.SUCCESS, run.getResult());
        assertTrue(run.getActions().stream()
                        .anyMatch(a -> SETUP_ACTION_CLASS_SIMPLE_NAME.equals(a.getClass().getSimpleName())),
                "build #" + number + " must still carry its stored setup action (build.xml)");
        assertEquals(goldenText(goldenStepLog(goldenKey)), stepLogLines(j.getLog(run), JOB),
                "stored console of old build #" + number);
    }

    private void assertMatchesGolden(WorkflowRun run, String jobName, String goldenKey) throws IOException {
        assertArrayEquals(goldenBytes(goldenDeployed(goldenKey)), logBytes(j, run, BIN),
                "deployed bytes must equal what the old code deployed");
        assertEquals(goldenText(goldenStepLog(goldenKey)), stepLogLines(j.getLog(run), jobName),
                "plugin console lines must equal what the old code printed");
    }

    // ---- persisted data ---------------------------------------------------------------------

    @Test
    @WithLocalData(FIXTURE)
    public void jobOverrideProperty_loadsWithAllVersionsChainAndActivePointer() {
        JobConfigTemplateProperty property = propertyOf(j, JOB);

        assertNotNull(property, "the job's override property must load from the old config.xml");
        assertEquals(2, property.getVersions().size());
        assertEquals(2, property.getActiveVersionNumber());
        assertEquals(OWN_V1, property.getVersion(1).getContentJson());
        assertEquals("first version café", property.getVersion(1).getNote());
        assertEquals(chainOf(BaseConfigReference.active(BASE), BaseConfigReference.pinned(BASE2, 1)),
                property.getVersion(1).getBaseChain());
        assertEquals(OWN_V2, property.getVersion(2).getContentJson());
    }

    @Test
    @WithLocalData(FIXTURE)
    public void storageDirectory_configSetsAndDeploymentBindingsLoad() {
        ConfigSetRepository sets = new ConfigSetRepository();
        ConfigSet base = sets.findCommon(BASE);
        assertNotNull(base);
        assertEquals(2, base.getVersions().size());
        assertEquals(2, base.getActiveVersionNumber());
        assertEquals(BASE_V1, base.getVersion(1).getContentJson());
        assertEquals(CRED, base.getSecretsManifest().get("Db.Password"));
        ConfigSet base2 = sets.findCommon(BASE2);
        assertNotNull(base2);
        assertEquals(2, base2.getVersions().size());

        ConfigDeploymentBindingRepository bindings = new ConfigDeploymentBindingRepository();
        List<ResolvedBaseVersion> frozenAtBuild1 = List.of(new ResolvedBaseVersion(BASE, 1),
                new ResolvedBaseVersion(BASE2, 1));
        ConfigDeploymentBinding binding1 = bindings.find(JOB + "#1");
        assertNotNull(binding1);
        assertEquals(frozenAtBuild1, binding1.getResolvedBaseChain());
        assertEquals(1, binding1.getOwnConfigVersionNumber());
        ConfigDeploymentBinding binding2 = bindings.find(JOB + "#2");
        assertNotNull(binding2);
        assertEquals(List.of(new ResolvedBaseVersion(BASE, 2), new ResolvedBaseVersion(BASE2, 1)),
                binding2.getResolvedBaseChain());
        assertEquals(2, binding2.getOwnConfigVersionNumber());
        ConfigDeploymentBinding binding3 = bindings.find(JOB + "#3");
        assertNotNull(binding3, "the redeploy build forward-chained its own binding");
        assertEquals(frozenAtBuild1, binding3.getResolvedBaseChain());
        assertEquals(1, binding3.getOwnConfigVersionNumber());
    }

    @Test
    @WithLocalData(FIXTURE)
    public void finishedOldBuilds_loadWithResultStoredSetupActionAndConsole() throws Exception {
        assertFinishedOldBuild(1, G_BUILD1);
        assertFinishedOldBuild(2, G_BUILD2);
        assertFinishedOldBuild(3, G_BUILD3);
    }

    // ---- new builds on the old home ---------------------------------------------------------

    @Test
    @WithLocalData(FIXTURE)
    public void newLiveDeploy_onTheUpgradedHome_producesTheOldCodesGoldenBytesAndConsole() throws Exception {
        WorkflowRun run = runScript(j, job(JOB), Result.SUCCESS, liveDeployScript());

        assertMatchesGolden(run, JOB, G_BUILD2);
    }

    @Test
    @WithLocalData(FIXTURE)
    public void redeployOfBuildShippedByTheOldCode_replaysItsFrozenBindingByteForByte() throws Exception {
        WorkflowRun run = runScript(j, job(JOB), Result.SUCCESS, redeployOfBuild1Script());

        assertMatchesGolden(run, JOB, G_BUILD3);
        assertArrayEquals(goldenBytes(goldenDeployed(G_BUILD1)), logBytes(j, run, BIN),
                "a redeploy of build #1 must equal what build #1 originally shipped");
    }

    // ---- in-flight builds (suspended by the old code) ---------------------------------------

    private void resumeAndFinish(String jobName) throws Exception {
        WorkflowRun run = job(jobName).getLastBuild();
        assertNotNull(run, "the suspended build of '" + jobName + "' must load");
        assertTrue(run.isBuilding(), "the build was suspended mid-run and must still be in progress");

        run.setDescription(GO);
        j.assertBuildStatusSuccess(j.waitForCompletion(run));

        assertMatchesGolden(run, jobName, G_INFLIGHT);
    }

    @Test
    @WithLocalData(FIXTURE)
    public void buildSuspendedRightAfterSetup_resumesAndRunsValidateAndSubstituteWithGoldenOutput()
            throws Exception {
        resumeAndFinish(IF_JOB_1);
    }

    @Test
    @WithLocalData(FIXTURE)
    public void buildSuspendedAfterSetupAndValidate_resumesAndRunsSubstituteWithGoldenOutput() throws Exception {
        resumeAndFinish(IF_JOB_2);
    }
}
